name: Build, test and push awesomesauce container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_USERNAME: skalelabs
        DOCKER_PASSWORD: ${{ secrets.DOCKER_SECRET }}
    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_SECRET }}
      run: docker login -u skalelabs -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: build container for release
      if: contains(github.ref, 'develop') || contains(github.ref, 'beta') || contains(github.ref, 'master') || contains(github.ref, 'stable')
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch $BRANCH"
        export VERSION=$(cat VERSION)
        echo "Version $VERSION"
        export VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $VERSION)
        echo "::set-env name=VERSION::$VERSION"
        echo "Version $VERSION"
        bash ./scripts/build_image.sh Dockerfile awesomesauce
    - name: build container for testing
      run: python3 scripts/docker_build.py Dockerfile awesomesauce ${GITHUB_SHA}
    - name: deploy docker image
      if: contains(github.ref, 'develop') || contains(github.ref, 'beta') || contains(github.ref, 'master') || contains(github.ref, 'stable')
      run : |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch $BRANCH"
        export VERSION=${{env.VERSION}}
        echo "::set-env name=VERSION::$VERSION"
        echo "Version $VERSION"
        export RELEASE=true
        echo "::set-env name=RELEASE::$RELEASE"
        bash ./scripts/publish_image.sh awesomesauce
    - name: Create Release
      if: contains(github.ref, 'develop') || contains(github.ref, 'beta') || contains(github.ref, 'master') || contains(github.ref, 'stable')
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        draft: false
        prerelease: true
